name: Run & Publish
permissions:
  contents: read
  id-token: write
on:
  release:
    types: [published, edited]  
jobs:
  build-and-test:
    uses: ./.github/workflows/build.yml
  run:
    runs-on: 'ubuntu-latest'
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - run: ./bin/run.js plugins install @xeel-dev/cli-npm-plugin
      - run: ./bin/run.js plugins install @xeel-dev/cli-docker-plugin
      - run: ./bin/run.js dependency-debt report --auth github --organization "x::org:64jlQszyh97h4u4d0IGc7J" --repository "$GITHUB_REPOSITORY_ID"
        env:
          XEEL_API: 'https://api.xeel-dev.com' # Use the development API
          XEEL_APP: 'https://app.xeel-dev.com' # Use the development APP
  publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - uses: JS-DevTools/npm-publish@v3
        id: publish
        with:
          access: public
          provenance: true
          token: ${{ secrets.NPM_TOKEN }}
      - name: Send release to Discord
        if: ${{ steps.publish.outputs.type }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
            -d "{\"content\": \"🚀 **New Release Published: [$GITHUB_REPOSITORY@$GITHUB_REF_NAME](https://github.com/$GITHUB_REPOSITORY/releases/tag/$GITHUB_REF_NAME)**\"}" \
            "$DISCORD_WEBHOOK_URL"
